specVersion: 0.2.0
name: parascan-subql-starter
version: 1.0.0
description: subql starter for parascan
repository: "https://github.com/warewar1/parascan-subql-starter"
schema:
  file: ./schema.graphql

network:
  endpoint: wss://192.227.174.177:8546
  genesisHash: "0xf7a21fad9c169a13991b6b1ba28198105dfca2d8ef93c9e40fafb4640e5723c1"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
