specVersion: 0.2.0
name: parascan-subql-starter
version: 1.0.0
description: subql starter for parascan
repository: "https://github.com/warewar1/parascan-subql-starter"
schema:
  file: ./schema.graphql

network:
  endpoint: wss://185.243.56.244:82
  genesisHash: "0xa967974c966921650dedea2a09b1effbbdbc97866e94adbb2c22a240d58d384c"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
